import { defineConfig } from 'tsdown'

/**
 * Build the package root as an independent Node bundle.
 *
 * This package contributes no browser half: its `/typert` and `/remote`
 * artifacts are generated by the root Typert plugin during the Host pass, and
 * the browser side reaches the namespace through the api-remotes assembly.
 */
export default defineConfig([
  {
    entry: ['lib/types/index.js'],
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
  },
])
